package tool_events

const (
	AUC_SRVC  = "AUCTIONS_SERVICE"
	AUTH_SRVC = "AUTH_SERVICE"
	RUN_SRVC  = "RUN_AUCTIONS_SERVICE"
	MNG_SRVC  = "MANAGE_AUCTIONS_SERVICE"
	PAY_SRVC  = "PAYMENT_SERVICE"
	SRC_SRVC  = "SEARCH_SERVICE"
)
